# Generated by Django 3.2.9 on 2021-11-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='twitt',
            table='tweet',
        ),
    ]
