# Generated by Django 3.2.9 on 2021-11-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitts', '0002_alter_twitt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitt',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=14, verbose_name='Name'),
        ),
    ]
