# Generated by Django 3.2.9 on 2021-11-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitts', '0003_alter_twitt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
