# Generated by Django 3.2.9 on 2021-11-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitts', '0005_alter_twitt_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitt',
            old_name='pic',
            new_name='image',
        ),
    ]
